/*
 * This source file was generated by the Gradle 'init' task
 */
package solido;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Solido test = new Sfera(12, 20);
        Solido test2 = new Cubo(12, 20);

        System.out.println(test.peso());
        System.out.println(test2.peso()+"\n");

        System.out.println(test.volume());
        System.out.println(test2.volume());

        //System.out.println(test2.getLato());
        System.out.println(((Cubo)test2).getLato());
    }
}
